// Airbnb listing photos per property — keyed by the ACTIVE property row's
// name (as stored in the DB). Photos are in Airbnb photo-tour order (hero
// first), scraped at 1920px and self-hosted in the Supabase `property-images`
// bucket, with room captions that drive the gallery grouping, the room
// showcase, and the semantic photo allocation on the booking page.

export type AirbnbPhoto = { url: string; caption?: string };

type AirbnbPhotoSet = {
  airbnbId: string;
  photos: (string | AirbnbPhoto)[];
};

const AIRBNB_PHOTOS: Record<string, AirbnbPhotoSet> = {
  // Airbnb 52923530 — Mansion/BML — 72 photos (scraped Jul 2026)
  "Lakefront Mansion w/ 3 Decks, Hot Tub, Boats, & Game Room!": {
    airbnbId: "52923530",
    photos: [
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368901/airbnb/01-living-room-image-1.jpg", caption: "Living room" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368901/airbnb/02-living-room-image-2.jpg", caption: "Living room" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368901/airbnb/03-living-room-image-3.jpg", caption: "Living room" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368901/airbnb/04-living-room-image-4.jpg", caption: "Living room" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368901/airbnb/05-living-room-image-5.jpg", caption: "Living room" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368901/airbnb/06-full-kitchen-image-1.jpg", caption: "Full kitchen" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368901/airbnb/07-full-kitchen-image-2.jpg", caption: "Full kitchen" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368901/airbnb/08-dining-area-1-image-1.jpg", caption: "Dining area 1" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368901/airbnb/09-dining-area-1-image-2.jpg", caption: "Dining area 1" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368901/airbnb/10-dining-area-2-image-1.jpg", caption: "Dining area 2" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368901/airbnb/11-bedroom-1-image-1.jpg", caption: "Bedroom 1" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368901/airbnb/12-bedroom-1-image-2.jpg", caption: "Bedroom 1" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368901/airbnb/13-bedroom-1-image-3.jpg", caption: "Bedroom 1" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368901/airbnb/14-bedroom-2-image-1.jpg", caption: "Bedroom 2" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368901/airbnb/15-bedroom-3-image-1.jpg", caption: "Bedroom 3" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368901/airbnb/16-bedroom-4-image-1.jpg", caption: "Bedroom 4" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368901/airbnb/17-bedroom-4-image-2.jpg", caption: "Bedroom 4" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368901/airbnb/18-bedroom-5-image-1.jpg", caption: "Bedroom 5" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368901/airbnb/19-bedroom-5-image-2.jpg", caption: "Bedroom 5" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368901/airbnb/20-full-bathroom-1-image-1.jpg", caption: "Full bathroom 1" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368901/airbnb/21-full-bathroom-2-image-1.jpg", caption: "Full bathroom 2" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368901/airbnb/22-full-bathroom-2-image-2.jpg", caption: "Full bathroom 2" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368901/airbnb/23-full-bathroom-2-image-3.jpg", caption: "Full bathroom 2" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368901/airbnb/24-full-bathroom-3-image-1.jpg", caption: "Full bathroom 3" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368901/airbnb/25-full-bathroom-3-image-2.jpg", caption: "Full bathroom 3" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368901/airbnb/26-half-bathroom-image-1.jpg", caption: "Half bathroom" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368901/airbnb/27-office-image-1.jpg", caption: "Office" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368901/airbnb/28-backyard-image-1.jpg", caption: "Backyard" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368901/airbnb/29-backyard-image-2.jpg", caption: "Backyard" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368901/airbnb/30-backyard-image-3.jpg", caption: "Backyard" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368901/airbnb/31-backyard-image-4.jpg", caption: "Backyard" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368901/airbnb/32-backyard-image-5.jpg", caption: "Backyard" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368901/airbnb/33-backyard-image-6.jpg", caption: "Backyard" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368901/airbnb/34-backyard-image-7.jpg", caption: "Backyard" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368901/airbnb/35-patio-image-1.jpg", caption: "Patio" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368901/airbnb/36-patio-image-2.jpg", caption: "Patio" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368901/airbnb/37-patio-image-3.jpg", caption: "Patio" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368901/airbnb/38-patio-image-4.jpg", caption: "Patio" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368901/airbnb/39-patio-image-5.jpg", caption: "Patio" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368901/airbnb/40-patio-image-6.jpg", caption: "Patio" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368901/airbnb/41-patio-image-7.jpg", caption: "Patio" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368901/airbnb/42-patio-image-8.jpg", caption: "Patio" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368901/airbnb/43-patio-image-9.jpg", caption: "Patio" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368901/airbnb/44-patio-image-10.jpg", caption: "Patio" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368901/airbnb/45-patio-image-11.jpg", caption: "Patio" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368901/airbnb/46-patio-image-12.jpg", caption: "Patio" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368901/airbnb/47-laundry-area-image-1.jpg", caption: "Laundry area" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368901/airbnb/48-gym-image-1.jpg", caption: "Gym" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368901/airbnb/49-gym-image-2.jpg", caption: "Gym" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368901/airbnb/50-exterior-1-image-1.jpg", caption: "Exterior 1" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368901/airbnb/51-exterior-1-image-2.jpg", caption: "Exterior 1" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368901/airbnb/52-exterior-1-image-3.jpg", caption: "Exterior 1" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368901/airbnb/53-exterior-1-image-4.jpg", caption: "Exterior 1" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368901/airbnb/54-exterior-2-image-1.jpg", caption: "Exterior 2" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368901/airbnb/55-hot-tub-image-1.jpg", caption: "Hot tub" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368901/airbnb/56-couch-opens-to-a-queen-pull-out.jpg", caption: "Couch opens to a queen pull out" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368901/airbnb/57-event-room-image-2.jpg", caption: "Event room" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368901/airbnb/58-event-room-image-3.jpg", caption: "Event room" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368901/airbnb/59-game-room-image-1.jpg", caption: "Game room" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368901/airbnb/60-game-room-image-2.jpg", caption: "Game room" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368901/airbnb/61-game-room-image-3.jpg", caption: "Game room" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368901/airbnb/62-game-room-image-4.jpg", caption: "Game room" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368901/airbnb/63-game-room-image-5.jpg", caption: "Game room" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368901/airbnb/64-game-room-image-6.jpg", caption: "Game room" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368901/airbnb/65-additional-photos-image-1.jpg", caption: "Sauna" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368901/airbnb/66-additional-photos-image-2.jpg", caption: "Sauna" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368901/airbnb/67-additional-photos-image-3.jpg", caption: "Bathroom" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368901/airbnb/68-additional-photos-image-4.jpg", caption: "Bathroom" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368901/airbnb/69-additional-photos-image-5.jpg", caption: "Aerial view" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368901/airbnb/70-additional-photos-image-6.jpg", caption: "Aerial view" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368901/airbnb/71-additional-photos-image-7.jpg", caption: "Aerial view" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368901/airbnb/72-additional-photos-image-8.jpg", caption: "Aerial view" },
    ],
  },

  // Airbnb 44618068 — Lakehouse — 72 photos (scraped Jul 2026; replaces the
  // 8 stale hotlinked URLs that had left this page nearly photoless)
  "Poconos Lakefront with Hot Tub, boats, and more!": {
    airbnbId: "44618068",
    photos: [
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355872/airbnb/01-additional-photos-image-1.jpg", caption: "Exterior" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355872/airbnb/02-living-room-1-image-1.jpg", caption: "Living room 1" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355872/airbnb/03-living-room-1-image-2.jpg", caption: "Living room 1" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355872/airbnb/04-living-room-1-image-3.jpg", caption: "Living room 1" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355872/airbnb/05-living-room-1-image-4.jpg", caption: "Living room 1" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355872/airbnb/06-living-room-1-image-5.jpg", caption: "Living room 1" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355872/airbnb/07-living-room-2-image-1.jpg", caption: "Living room 2" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355872/airbnb/08-living-room-2-image-2.jpg", caption: "Living room 2" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355872/airbnb/09-living-room-2-image-3.jpg", caption: "Living room 2" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355872/airbnb/10-full-kitchen-image-1.jpg", caption: "Full kitchen" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355872/airbnb/11-full-kitchen-image-2.jpg", caption: "Full kitchen" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355872/airbnb/12-full-kitchen-image-3.jpg", caption: "Full kitchen" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355872/airbnb/13-dining-area-1-image-1.jpg", caption: "Dining area 1" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355872/airbnb/14-dining-area-2-image-1.jpg", caption: "Dining area 2" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355872/airbnb/15-dining-area-2-image-2.jpg", caption: "Dining area 2" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355872/airbnb/16-bedroom-1-image-1.jpg", caption: "Bedroom 1" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355872/airbnb/17-bedroom-1-image-2.jpg", caption: "Bedroom 1" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355872/airbnb/18-bedroom-2-image-1.jpg", caption: "Bedroom 2" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355872/airbnb/19-bedroom-2-image-2.jpg", caption: "Bedroom 2" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355872/airbnb/20-bedroom-3-image-1.jpg", caption: "Bedroom 3" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355872/airbnb/21-bedroom-3-image-2.jpg", caption: "Bedroom 3" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355872/airbnb/22-bedroom-4-image-1.jpg", caption: "Bedroom 4" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355872/airbnb/23-bedroom-4-image-2.jpg", caption: "Bedroom 4" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355872/airbnb/24-bedroom-5-image-1.jpg", caption: "Bedroom 5" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355872/airbnb/25-bedroom-5-image-2.jpg", caption: "Bedroom 5" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355872/airbnb/26-full-bathroom-1-image-1.jpg", caption: "Full bathroom 1" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355872/airbnb/27-full-bathroom-1-image-2.jpg", caption: "Full bathroom 1" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355872/airbnb/28-full-bathroom-1-image-3.jpg", caption: "Full bathroom 1" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355872/airbnb/29-full-bathroom-2-image-1.jpg", caption: "Full bathroom 2" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355872/airbnb/30-full-bathroom-2-image-2.jpg", caption: "Full bathroom 2" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355872/airbnb/31-full-bathroom-2-image-3.jpg", caption: "Full bathroom 2" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355872/airbnb/32-full-bathroom-2-image-4.jpg", caption: "Full bathroom 2" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355872/airbnb/33-full-bathroom-2-image-5.jpg", caption: "Full bathroom 2" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355872/airbnb/34-full-bathroom-3-image-1.jpg", caption: "Full bathroom 3" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355872/airbnb/35-full-bathroom-3-image-2.jpg", caption: "Full bathroom 3" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355872/airbnb/36-backyard-image-1.jpg", caption: "Backyard" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355872/airbnb/37-backyard-image-2.jpg", caption: "Backyard" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355872/airbnb/38-backyard-image-3.jpg", caption: "Backyard" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355872/airbnb/39-backyard-image-4.jpg", caption: "Backyard" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355872/airbnb/40-backyard-image-5.jpg", caption: "Backyard" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355872/airbnb/41-backyard-image-6.jpg", caption: "Backyard" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355872/airbnb/42-backyard-image-7.jpg", caption: "Backyard" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355872/airbnb/43-view-of-our-newly-landscaped-yard-from-the-hot-tub.jpg", caption: "View of our newly landscaped yard from the hot tub" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355872/airbnb/44-newly-landscaped-fire-pit-area.jpg", caption: "Newly landscaped fire pit area" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355872/airbnb/45-landscaped-path-to-lake-deck.jpg", caption: "Landscaped path to lake deck" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355872/airbnb/46-lake-dock.jpg", caption: "Lake dock" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355872/airbnb/47-view-of-the-backyard-lake.jpg", caption: "View of the backyard lake" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355872/airbnb/48-backyard-image-13.jpg", caption: "Backyard" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355872/airbnb/49-patio-image-1.jpg", caption: "Patio" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355872/airbnb/50-patio-image-2.jpg", caption: "Patio" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355872/airbnb/51-deck-image-1.jpg", caption: "Deck" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355872/airbnb/52-laundry-area-image-1.jpg", caption: "Laundry area" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355872/airbnb/53-front-of-the-house.jpg", caption: "Front of the house" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355872/airbnb/54-pool-image-1.jpg", caption: "Pool" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355872/airbnb/55-community-pool.jpg", caption: "Community Pool" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355872/airbnb/56-hot-tub-image-1.jpg", caption: "Hot tub" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355872/airbnb/57-game-room-image-1.jpg", caption: "Game room" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355872/airbnb/58-game-room-image-2.jpg", caption: "Game room" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355872/airbnb/59-game-room-image-3.jpg", caption: "Game room" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355872/airbnb/60-sunroom-image-1.jpg", caption: "Sunroom" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355872/airbnb/61-additional-photos-image-2.jpg", caption: "Aerial view" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355872/airbnb/62-additional-photos-image-3.jpg", caption: "Aerial view" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355872/airbnb/63-bushkill-falls-15-min-drive.jpg", caption: "Bushkill Falls (15 min drive)" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355872/airbnb/64-camelback-mountain-15-min-drive.jpg", caption: "Camelback Mountain (15 min drive)" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355872/airbnb/65-downtown-east-stroudberg.jpg", caption: "Downtown East Stroudsburg" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355872/airbnb/66-shawnee-mountain-25-min-drive.jpg", caption: "Shawnee Mountain (25 min drive)" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355872/airbnb/67-bushkill-riding-stables-15-min-drive.jpg", caption: "Bushkill Riding Stables (15 min drive)" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355872/airbnb/68-crossings-premium-outlets-12-min-drive.jpg", caption: "Crossings Premium Outlets (12 min drive)" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355872/airbnb/69-downtown-east-stroudsburg.jpg", caption: "Downtown East Stroudsburg" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355872/airbnb/70-additional-photos-image-11.jpg", caption: "Exterior" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355872/airbnb/71-gazebo-and-lake-beach-10-min-walk-from-the-house.jpg", caption: "Gazebo and Lake Beach (10 min walk from the house)" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355872/airbnb/72-soccer-baseball-basketball-and-tennis-fields-courts-are-avai.jpg", caption: "Soccer, baseball, basketball, and tennis fields/courts are available for your enjoyment!" },
    ],
  },

  // Airbnb 51672067 — Bianca's — 47 photos (scraped Jun 2026; captions
  // derived from the archived filenames)
  "Cozy Lakefront Home w/ Game Room, Hot Tub, Fire Pit, & Boats": {
    airbnbId: "51672067",
    photos: [
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368827/airbnb/01-photo.jpg", caption: "Living room" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368827/airbnb/02-living-room-image-2.jpg", caption: "Living room" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368827/airbnb/03-living-room-image-3.jpg", caption: "Living room" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368827/airbnb/04-living-room-image-4.jpg", caption: "Living room" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368827/airbnb/05-full-kitchen-image-1.jpg", caption: "Full kitchen" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368827/airbnb/06-full-kitchen-image-2.jpg", caption: "Full kitchen" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368827/airbnb/07-full-kitchen-image-3.jpg", caption: "Full kitchen" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368827/airbnb/08-dining-area-image-1.jpg", caption: "Dining area" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368827/airbnb/09-dining-area-image-3.jpg", caption: "Dining area" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368827/airbnb/10-bedroom-1.jpg", caption: "Bedroom 1" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368827/airbnb/11-bedroom-1-image-2.jpg", caption: "Bedroom 1" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368827/airbnb/12-bedroom-1-image-3.jpg", caption: "Bedroom 1" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368827/airbnb/13-bedroom-2.jpg", caption: "Bedroom 2" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368827/airbnb/14-bedroom-2-image-2.jpg", caption: "Bedroom 2" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368827/airbnb/15-bedroom-2-image-3.jpg", caption: "Bedroom 2" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368827/airbnb/16-bedroom-3.jpg", caption: "Bedroom 3" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368827/airbnb/17-full-bathroom-1-image-1.jpg", caption: "Full bathroom" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368827/airbnb/18-full-bathroom-2-image-2.jpg", caption: "Full bathroom" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368827/airbnb/19-full-bathroom-2-image-3.jpg", caption: "Full bathroom" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368827/airbnb/20-backyard-image-1.jpg", caption: "Backyard" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368827/airbnb/21-backyard-image-2.jpg", caption: "Backyard" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368827/airbnb/22-patio-image-1.jpg", caption: "Patio" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368827/airbnb/23-patio-image-2.jpg", caption: "Patio" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368827/airbnb/24-patio-image-3.jpg", caption: "Patio" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368827/airbnb/25-patio-image-4.jpg", caption: "Patio" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368827/airbnb/26-inflatable-screen-with-projector.jpg", caption: "Inflatable screen with projector" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368827/airbnb/27-inflatable-screen-with-projector.jpg", caption: "Inflatable screen with projector" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368827/airbnb/28-laundry-area-image-1.jpg", caption: "Laundry area" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368827/airbnb/29-exterior-image-1.jpg", caption: "Exterior" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368827/airbnb/30-game-room-image-1.jpg", caption: "Game room" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368827/airbnb/31-game-room-image-2.jpg", caption: "Game room" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368827/airbnb/32-game-room-image-3.jpg", caption: "Game room" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368827/airbnb/33-game-room-image-4.jpg", caption: "Game room" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368827/airbnb/34-game-room-image-5.jpg", caption: "Game room" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368827/airbnb/35-game-room-image-6.jpg", caption: "Game room" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368827/airbnb/36-additional-photos-image-2.jpg", caption: "Hallway" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368827/airbnb/37-additional-photos-image-5.jpg", caption: "Exterior" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368827/airbnb/38-additional-photos-image-6.jpg", caption: "Lake view" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368827/airbnb/39-additional-photos-image-7.jpg", caption: "Lake view" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368827/airbnb/40-additional-photos-image-8.jpg", caption: "Exterior" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368827/airbnb/41-additional-photos-image-9.jpg", caption: "Backyard" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368827/airbnb/42-additional-photos-image-10.jpg", caption: "Dining area" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368827/airbnb/43-additional-photos-image-11.jpg", caption: "Backyard" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368827/airbnb/44-additional-photos-image-12.jpg", caption: "Dining area" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368827/airbnb/45-additional-photos-image-13.jpg", caption: "Game room" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368827/airbnb/46-additional-photos-image-14.jpg", caption: "Backyard" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-368827/airbnb/47-additional-photos-image-15.jpg", caption: "Game room" },
    ],
  },

  // Airbnb 49400408 — Manor — 56 photos (scraped Jul 2026)
  "Lake Adjacent Home w/ Hot Tub, Game Room, Boats, Fenced Yard": {
    airbnbId: "49400408",
    photos: [
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355871/airbnb/01-gorgeous-lakefront-colonial-exterior.jpg", caption: "Gorgeous Lakefront Colonial exterior" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355871/airbnb/02-listing-image-2.jpg", caption: "Backyard" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355871/airbnb/03-listing-image-3.jpg", caption: "Game room" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355871/airbnb/04-listing-image-4.jpg", caption: "Living room" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355871/airbnb/05-listing-image-5.jpg", caption: "Deck" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355871/airbnb/06-listing-image-6.jpg", caption: "Home theater" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355871/airbnb/07-listing-image-7.jpg", caption: "Aerial view" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355871/airbnb/08-listing-image-8.jpg", caption: "Bedroom" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355871/airbnb/09-listing-image-9.jpg", caption: "Bedroom" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355871/airbnb/10-listing-image-10.jpg", caption: "Living room" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355871/airbnb/11-listing-image-11.jpg", caption: "Bathroom" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355871/airbnb/12-listing-image-12.jpg", caption: "Hallway" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355871/airbnb/13-listing-image-13.jpg", caption: "Living room" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355871/airbnb/14-listing-image-14.jpg", caption: "Kitchen" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355871/airbnb/15-listing-image-15.jpg", caption: "Kitchen" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355871/airbnb/16-listing-image-16.jpg", caption: "Kitchen" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355871/airbnb/17-listing-image-17.jpg", caption: "Kitchen" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355871/airbnb/18-listing-image-18.jpg", caption: "Kitchen" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355871/airbnb/19-listing-image-19.jpg", caption: "Dining area" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355871/airbnb/20-listing-image-20.jpg", caption: "Dining area" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355871/airbnb/21-listing-image-21.jpg", caption: "Bathroom" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355871/airbnb/22-listing-image-22.jpg", caption: "Bathroom" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355871/airbnb/23-listing-image-23.jpg", caption: "Entryway" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355871/airbnb/24-listing-image-24.jpg", caption: "Entryway" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355871/airbnb/25-listing-image-25.jpg", caption: "Loft" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355871/airbnb/26-listing-image-26.jpg", caption: "Bedroom" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355871/airbnb/27-listing-image-27.jpg", caption: "Bathroom" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355871/airbnb/28-listing-image-28.jpg", caption: "Bathroom" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355871/airbnb/29-listing-image-29.jpg", caption: "Bathroom" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355871/airbnb/30-listing-image-30.jpg", caption: "Bedroom" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355871/airbnb/31-listing-image-31.jpg", caption: "Bedroom" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355871/airbnb/32-listing-image-32.jpg", caption: "Bedroom" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355871/airbnb/33-listing-image-33.jpg", caption: "Bedroom" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355871/airbnb/34-listing-image-34.jpg", caption: "Bathroom" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355871/airbnb/35-backyard-lake-in-fall.jpg", caption: "Backyard lake in Fall" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355871/airbnb/36-listing-image-36.jpg", caption: "Deck" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355871/airbnb/37-listing-image-37.jpg", caption: "Lake view" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355871/airbnb/38-walk-down-to-the-lake-from-the-backyard.jpg", caption: "walk down to the lake from the backyard!" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355871/airbnb/39-listing-image-39.jpg", caption: "Aerial view" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355871/airbnb/40-community-pool.jpg", caption: "Community Pool" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355871/airbnb/41-gazebo-and-lake-beach-10-min-walk-from-the-house.jpg", caption: "Gazebo and Lake Beach (10 min walk from the house)" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355871/airbnb/42-soccer-baseball-basketball-and-tennis-fields-courts-are-avai.jpg", caption: "Soccer, baseball, basketball, and tennis fields/courts are available for your enjoyment!" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355871/airbnb/43-shawnee-mountain-25-min-drive.jpg", caption: "Shawnee Mountain (25 min drive)" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355871/airbnb/44-camelback-mountain-15-min-drive.jpg", caption: "Camelback Mountain (15 min drive)" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355871/airbnb/45-bushkill-riding-stables-15-min-drive.jpg", caption: "Bushkill Riding Stables (15 min drive)" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355871/airbnb/46-bushkill-falls-15-min-drive.jpg", caption: "Bushkill Falls (15 min drive)" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355871/airbnb/47-crossings-premium-outlets-12-min-drive.jpg", caption: "Crossings Premium Outlets (12 min drive)" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355871/airbnb/48-downtown-east-stroudsburg.jpg", caption: "Downtown East Stroudsburg" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355871/airbnb/49-listing-image-49.jpg", caption: "Deck" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355871/airbnb/50-listing-image-50.jpg", caption: "Game room" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355871/airbnb/51-listing-image-51.jpg", caption: "Game room" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355871/airbnb/52-listing-image-52.jpg", caption: "Game room" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355871/airbnb/53-downtown-east-stroudberg.jpg", caption: "Downtown East Stroudsburg" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355871/airbnb/54-listing-image-54.jpg", caption: "Deck" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355871/airbnb/55-listing-image-55.jpg", caption: "Patio" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-355871/airbnb/56-newly-installed-back-yard-sauna.jpg", caption: "Newly installed back yard sauna :)" },
    ],
  },

  "Lakeview Chalet w/ hot tub, sauna, fire pit & decks": {
    airbnbId: "49461808",
    photos: [
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-588691/airbnb/01-living-room-3-image-2.jpg", caption: "Living room 3" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-588691/airbnb/02-living-room-1-image-1.jpg", caption: "Living room 1" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-588691/airbnb/03-living-room-1-image-2.jpg", caption: "Living room 1" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-588691/airbnb/04-living-room-1-image-3.jpg", caption: "Living room 1" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-588691/airbnb/05-living-room-2-image-1.jpg", caption: "Living room 2" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-588691/airbnb/06-living-room-2-image-2.jpg", caption: "Living room 2" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-588691/airbnb/07-living-room-2-image-3.jpg", caption: "Living room 2" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-588691/airbnb/08-living-room-2-image-4.jpg", caption: "Living room 2" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-588691/airbnb/09-living-room-3-image-1.jpg", caption: "Living room 3" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-588691/airbnb/10-living-room-3-image-3.jpg", caption: "Living room 3" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-588691/airbnb/11-living-room-3-image-4.jpg", caption: "Living room 3" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-588691/airbnb/12-living-room-3-image-5.jpg", caption: "Living room 3" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-588691/airbnb/13-living-room-3-image-6.jpg", caption: "Living room 3" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-588691/airbnb/14-full-kitchen-image-1.jpg", caption: "Full kitchen" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-588691/airbnb/15-full-kitchen-image-2.jpg", caption: "Full kitchen" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-588691/airbnb/16-full-kitchen-image-3.jpg", caption: "Full kitchen" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-588691/airbnb/17-full-kitchen-image-4.jpg", caption: "Full kitchen" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-588691/airbnb/18-dining-area-image-1.jpg", caption: "Dining area" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-588691/airbnb/19-dining-area-image-2.jpg", caption: "Dining area" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-588691/airbnb/20-dining-area-image-3.jpg", caption: "Dining area" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-588691/airbnb/21-bedroom-1-image-1.jpg", caption: "Bedroom 1" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-588691/airbnb/22-bedroom-1-image-2.jpg", caption: "Bedroom 1" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-588691/airbnb/23-bedroom-1-image-3.jpg", caption: "Bedroom 1" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-588691/airbnb/24-bedroom-2-image-1.jpg", caption: "Bedroom 2" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-588691/airbnb/25-bedroom-2-image-2.jpg", caption: "Bedroom 2" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-588691/airbnb/26-bedroom-2-image-3.jpg", caption: "Bedroom 2" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-588691/airbnb/27-bedroom-2-image-4.jpg", caption: "Bedroom 2" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-588691/airbnb/28-bedroom-3-image-1.jpg", caption: "Bedroom 3" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-588691/airbnb/29-bedroom-3-image-2.jpg", caption: "Bedroom 3" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-588691/airbnb/30-bedroom-3-image-3.jpg", caption: "Bedroom 3" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-588691/airbnb/31-bedroom-3-image-4.jpg", caption: "Bedroom 3" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-588691/airbnb/32-bedroom-4-image-1.jpg", caption: "Bedroom 4" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-588691/airbnb/33-bedroom-4-image-2.jpg", caption: "Bedroom 4" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-588691/airbnb/34-bedroom-4-image-3.jpg", caption: "Bedroom 4" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-588691/airbnb/35-full-bathroom-1-image-1.jpg", caption: "Full bathroom 1" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-588691/airbnb/36-full-bathroom-1-image-2.jpg", caption: "Full bathroom 1" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-588691/airbnb/37-full-bathroom-2-image-1.jpg", caption: "Full bathroom 2" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-588691/airbnb/38-full-bathroom-2-image-2.jpg", caption: "Full bathroom 2" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-588691/airbnb/39-full-bathroom-2-image-3.jpg", caption: "Full bathroom 2" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-588691/airbnb/40-full-bathroom-3-image-1.jpg", caption: "Full bathroom 3" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-588691/airbnb/41-full-bathroom-3-image-2.jpg", caption: "Full bathroom 3" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-588691/airbnb/42-full-bathroom-3-image-3.jpg", caption: "Full bathroom 3" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-588691/airbnb/43-backyard-image-1.jpg", caption: "Backyard" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-588691/airbnb/44-backyard-image-2.jpg", caption: "Backyard" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-588691/airbnb/45-backyard-image-3.jpg", caption: "Backyard" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-588691/airbnb/46-backyard-image-4.jpg", caption: "Backyard" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-588691/airbnb/47-patio-image-1.jpg", caption: "Patio" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-588691/airbnb/48-gazebo-and-lake-beach-10-min-walk-from-the-house.jpg", caption: "Gazebo and Lake Beach (10 min walk from the house)" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-588691/airbnb/49-deck-image-1.jpg", caption: "Deck" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-588691/airbnb/50-deck-image-2.jpg", caption: "Deck" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-588691/airbnb/51-exterior-image-1.jpg", caption: "Exterior" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-588691/airbnb/52-community-pool.jpg", caption: "Community Pool" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-588691/airbnb/53-hot-tub-image-1.jpg", caption: "Hot tub" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-588691/airbnb/54-hot-tub-image-2.jpg", caption: "Hot tub" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-588691/airbnb/55-sunroom-image-1.jpg", caption: "Sunroom" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-588691/airbnb/56-sunroom-image-2.jpg", caption: "Sunroom" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-588691/airbnb/57-sunroom-image-3.jpg", caption: "Sunroom" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-588691/airbnb/58-sunroom-image-4.jpg", caption: "Sunroom" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-588691/airbnb/59-additional-photos-image-1.jpg", caption: "Hallway" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-588691/airbnb/60-additional-photos-image-2.jpg", caption: "Aerial view" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-588691/airbnb/61-view-of-the-lake-accross-the-street.jpg", caption: "View of the lake across the street" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-588691/airbnb/62-bushkill-falls-15-min-drive.jpg", caption: "Bushkill Falls (15 min drive)" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-588691/airbnb/63-downtown-east-stroudberg.jpg", caption: "Downtown East Stroudsburg" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-588691/airbnb/64-crossings-premium-outlets-12-min-drive.jpg", caption: "Crossings Premium Outlets (12 min drive)" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-588691/airbnb/65-camelback-mountain-15-min-drive.jpg", caption: "Camelback Mountain (15 min drive)" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-588691/airbnb/66-shawnee-mountain-25-min-drive.jpg", caption: "Shawnee Mountain (25 min drive)" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-588691/airbnb/67-bushkill-riding-stables-15-min-drive.jpg", caption: "Bushkill Riding Stables (15 min drive)" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-588691/airbnb/68-downtown-east-stroudsburg.jpg", caption: "Downtown East Stroudsburg" },
      { url: "https://arvbaoeszakyuxqhkogz.supabase.co/storage/v1/object/public/property-images/lodgify-588691/airbnb/69-soccer-baseball-basketball-and-tennis-fields-courts-are-avai.jpg", caption: "Soccer, baseball, basketball, and tennis fields/courts" },
    ],
  },
};

// Old (now-inactive) property rows for the same physical houses — resolve to
// the active row's photo set so any lingering references keep working.
const NAME_ALIASES: Record<string, string> = {
  "Lakeview Chalet w/ Hot Tub, Sauna, Decks, Boats, & Fire Pit!":
    "Lakeview Chalet w/ hot tub, sauna, fire pit & decks",
  "Lakefront Home w/ Hot Tub, Game Room, Deck, Boats, Fire Pit":
    "Poconos Lakefront with Hot Tub, boats, and more!",
};

function resolveSet(propertyName: string): AirbnbPhotoSet | null {
  return (
    AIRBNB_PHOTOS[NAME_ALIASES[propertyName] ?? propertyName] ?? null
  );
}

/** Look up Airbnb photos for a property by name. Returns photo URLs or null. */
export function getAirbnbPhotos(propertyName: string): string[] | null {
  const entry = resolveSet(propertyName);
  return entry
    ? entry.photos.map((p) => (typeof p === "string" ? p : p.url))
    : null;
}

/** Photos with room captions (when the set has them) for gallery/lightbox use. */
export function getAirbnbPhotoDetails(propertyName: string): AirbnbPhoto[] | null {
  const entry = resolveSet(propertyName);
  return entry
    ? entry.photos.map((p) => (typeof p === "string" ? { url: p } : p))
    : null;
}
